catalogs:
  dev:
    '@arethetypeswrong/core': ^0.18.2
    '@sxzz/eslint-config': ^7.0.3
    '@sxzz/prettier-config': ^2.2.1
    '@sxzz/test-utils': ^0.5.6
    '@types/debug': ^4.1.12
    '@types/node': ^24.0.3
    '@types/semver': ^7.7.0
    bumpp: ^10.2.0
    eslint: ^9.29.0
    lightningcss: ^1.30.1
    pkg-types: ^2.1.0
    prettier: ^3.5.3
    publint: ^0.3.12
    tsx: ^4.20.3
    typescript: ~5.8.3
    unplugin-lightningcss: ^0.4.1
    unplugin-unused: ^0.5.1
    vitest: ^3.2.4

  docs:
    '@unocss/eslint-plugin': ^66.2.3
    '@vueuse/core': ^13.4.0
    typedoc: ^0.28.5
    typedoc-plugin-markdown: ^4.7.0
    unocss: ^66.2.3
    vite: npm:rolldown-vite@latest
    vitepress: ^1.6.3
    vitepress-plugin-group-icons: ^1.6.0
    vitepress-plugin-llms: ^1.5.1
    vue: ^3.5.17

  prod:
    ansis: ^4.1.0
    cac: ^6.7.14
    chokidar: ^4.0.3
    debug: ^4.4.1
    diff: ^8.0.2
    empathic: ^2.0.0
    hookable: ^5.5.3
    rolldown: ^1.0.0-beta.18
    rolldown-plugin-dts: ^0.13.11
    semver: ^7.7.2
    tinyexec: ^1.0.1
    tinyglobby: ^0.2.14
    unconfig: ^7.3.2

ignoredBuiltDependencies:
  - rolldown
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
