catalogs:
  dev:
    '@oxc-node/core': ^0.0.27
    '@sxzz/eslint-config': ^7.0.1
    '@sxzz/prettier-config': ^2.2.1
    '@sxzz/test-utils': ^0.5.6
    '@types/debug': ^4.1.12
    '@types/diff': ^7.0.2
    '@types/node': ^22.15.17
    '@types/semver': ^7.7.0
    bumpp: ^10.1.0
    eslint: ^9.26.0
    lightningcss: ^1.29.3
    pkg-types: ^2.1.0
    prettier: ^3.5.3
    publint: ^0.3.12
    tsup: ^8.4.0
    typescript: ~5.8.3
    unplugin-lightningcss: ^0.4.0
    unplugin-unused: ^0.5.0
    vitest: ^3.1.3

  docs:
    '@unocss/eslint-plugin': ^66.1.1
    typedoc: ^0.28.4
    typedoc-plugin-markdown: ^4.6.3
    unocss: ^66.1.1
    vite: ^6.3.5
    vitepress: ^1.6.3
    vitepress-plugin-group-icons: ^1.5.2
    vitepress-plugin-llms: ^1.1.3
    vue: ^3.5.13

  prod:
    ansis: ^4.0.0
    cac: ^6.7.14
    chokidar: ^4.0.3
    debug: ^4.4.0
    diff: ^7.0.0
    empathic: ^1.1.0
    hookable: ^5.5.3
    rolldown: 1.0.0-beta.8-commit.534fde3
    rolldown-plugin-dts: ^0.11.4
    semver: ^7.7.1
    tinyexec: ^1.0.1
    tinyglobby: ^0.2.13
    unconfig: ^7.3.2

ignoredBuiltDependencies:
  - rolldown
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
